# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 652ec79f1b1da2c046047fbf98b24602dc704566d9d0df0976f34a56abd6cec2fa90035298eb8615563b7ff012a2d5e07b3666c619bf9e9e1f25ae25a04ae722

test:
  secret_key_base: e2108c44cb258545702858f57754d9209b48ef205cf612d7ae13827c0c0b457c4e326aaab963c8d204aaa6aad7513033fad3e33ce88d0711c95c74c3e89d3b35

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
